unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# status bar color
set-option -g status-bg colour235
set-option -g status-fg yellow

# clipboard
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe 'xclip -in -selection clipboard &> /dev/null'
bind -T copy-mode-vi Enter send-keys -X cancel

# shortcut for moving tmux buffer to clipboard 
# mouse
bind-key -nr C-y run "tmux show-buffer | xclip -in -selection clipboard &> /dev/null"

# avoid ESC delay
set -s escape-time 0

# fix titlebar
set -g set-titles on
set -g set-titles-string "#T"

# mouse
setw -g mouse on

# scroll history
set -g history-limit 30000

# set ability to capture on start and restore on exit window data when running an application
set -g alternate-screen on

